name: Greetings

on: [pull_request]

jobs:
  pr-comment:
    name: PR Comment
    runs-on: [ubuntu-latest]
    steps:
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Oi, worker bee :tada:! Puttin it on :robot: :heart:'
