name: ZEIT Now Deployment
on:
- pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2.0.1
        with:
          zeit-token: ${{ secrets.ZeitToken }}
          github-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment: false
          working-directory: docs
          now-project-id: nowsy-test
