name: ZEIT Now Deployment
on:
- pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Deploy to now.sh                  # requires .now/project.json checked in
        env:
          ZEIT_TOKEN: ${{ secrets.ZeitToken }}
          BUILD_ID: ${{ github.sha }}
        run: >
          npx now deploy
          --build-env BUILD_ID=${BUILD_ID}
          --public
          --no-clipboard
          --token ${ZEIT_TOKEN}
          > deploy-url.txt
      - name: Set deploy url to env variable
        run: echo "::set-env name=ZEIT_DEPLOY::$(cat deploy-url.txt)"
      - name: Alias with PR number
        env:
          ZEIT_TOKEN: ${{ secrets.ZeitToken }}
        run: >
          npx now alias
          --token ${ZEIT_TOKEN}
          `cat deploy-url.txt`
          nowsy-test-pr-${{ github.event.number }}.now.sh
