name: ZEIT Now Deployment
on:
- pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: echo "Deploying PR with now..."
      - run: npx now --debug --no-clipboard --token ${{ secrets.ZeitToken }} > deploy.txt
      - run: echo "::set-env name=ZEIT_DEPLOY::$(cat deploy.txt)"
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Oi, worker bee :tada:! Puttin it on :robot: :heart: ${{ env.ZEIT_DEPLOY }}'