name: ZEIT Now Deployment
on:
- pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: echo "Deploying PR with now..."
      - name: deploy
        env:
          ZEIT_TOKEN: ${{ secrets.ZeitToken }}
          BUILD_ID: ${{ github.sha }}
        run: >
          now deploy
          --debug
          --build-env NODE_ENV=production
          --build-env BUILD_ID=${BUILD_ID}
          --env NODE_ENV=production
          --public
          --no-clipboard
          --token ${ZEIT_TOKEN}
          > deploy-url.txt
      - run: echo "::set-env name=ZEIT_DEPLOY::$(cat deploy-url.txt)"
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Oi, worker bee :tada:! Puttin it on :robot: :heart: ${{ env.ZEIT_DEPLOY }}'