name: ZEIT Now Deployment
on:
- pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: echo "Deploying PR with now..."
      - name: deploy
        env:
          ZEIT_TOKEN: ${{ secrets.ZeitToken }}
          BUILD_ID: ${{ github.sha }}
        run: >
          npx now deploy
          --build-env BUILD_ID=${BUILD_ID}
          --public
          --no-clipboard
          --token ${ZEIT_TOKEN}
          > deploy-url.txt
      - run: cat deploy-url.txt
      - run: echo "::set-env name=ZEIT_DEPLOY::$(cat deploy-url.txt)"
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Oi, worker bee :tada:! Puttin it on :robot: :heart: ${ZEIT_DEPLOY}"